{ pkgs, config, ... }:

{
  # Generated by explicit.
  # Detected markers: mix.exs
  # Detected manifests: none
  # - Detected rustler in the Elixir dependencies; enabling Rust because Rustler-backed NIFs need a Rust toolchain.
  packages = [
    # Added for the detected `actionlint` project requirements.
    pkgs.actionlint
    # Needed by explicit for repository inspection and generated hook workflows.
    pkgs.git
    # Needed by explicit runtime support inside generated environments.
    pkgs.jq
    # Needed to launch the sandboxed agent shell.
    pkgs.nono
  ];
  # Detected Elixir source files in the repository.
  languages.elixir.enable = true;
  # Enabling Rust because Rustler-backed NIFs need a Rust toolchain.
  languages.rust.enable = true;
}
